#!/bin/bash
ln -sF ~/dotfiles/.vimrc ~/.vimrc
ln -sF ~/dotfiles/.zshrc ~/.zshrc
ln -sF ~/dotfiles/.tmux.conf ~/.tmux.conf
ln -sF ~/dotfiles/.viminfo ~/.viminfo
ln -sF ~/dotfiles/.dir_colors ~/.dir_colors
ln -sF ~/dotfiles/.ideavimrc ~/.ideavimrc
ln -sF ~/dotfiles/.xvimrc ~/.xvimrc
ln -sF ~/dotfiles/.gitignore_global ~/.gitignore_global
ln -sF ~/dotfiles/.http.zsh ~/.http.zsh
